spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: gather-servie
          uri: lb://GATHER-SERVICE
          predicates:
            - Path=/gather-service/**
            - Method=GET, POST
          filters:
            - RewritePath=/gather-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: LoggingFilter
          args:
            baseMessage: Gateway Service Logger
            preLogger: true
            postLogger: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8000